In [1]:
import pandas as pd
import numpy as np
import requests
import bs4 as bs
import urllib.request

Extracting features of 2020 movies from Wikipedia

In [2]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2020"

In [3]:
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]
#as there are 4 tables holding movie data
#for 2018 data

In [4]:
df = df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)
df

C:\Users\HP\Anaconda3\lib\site-packages\pandas\core\frame.py:7123: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort,

,.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref.,Cast and crew,Opening,Opening.1,Production company,Ref.,Title
0,[2],Nicolas Pesce (director/screenplay); Andrea Ri...,JANUARY,3,Screen Gems / Stage 6 Films / Ghost House Pict...,NaN,The Grudge
1,[3],"William Eubank (director); Brian Duffield, Ada...",JANUARY,10,20th Century Fox / TSG Entertainment / Chernin...,NaN,Underwater
2,[4],"Miguel Arteta (director); Sam Pitman, Adam Col...",JANUARY,10,Paramount Pictures,NaN,Like a Boss
3,NaN,Jon Avnet (director/screenplay); Eric Nazarian...,JANUARY,10,IFC Films,NaN,Three Christs
4,[5],Anthony Jerjen (director); Andrew Crabtree (sc...,JANUARY,10,Barry Films / Tycor International Film Company,NaN,Inherit the Viper
...,...,...,...,...,...,...,...
270,NaN,Robert Rodriguez (director/screenplay); Priyan...,DECEMBER,25,Netflix / Troublemaker Studios,[241],We Can Be Heroes
271,NaN,Paul Greengrass (director/screenplay); Luke Da...,DECEMBER,25,Universal Pictures / Perfect World Pictures,[242],News of the World
272,NaN,Regina King (director); Kemp Powers (screenpla...,DECEMBER,25,Amazon Studios,[243],One Night in Miami...
273,NaN,Emerald Fennell (director/screenplay); Carey M...,DECEMBER,25,Focus Features / FilmNation Entertainment,[244],Promising Young Woman
274,NaN,Kornél Mundruczó (director); Kata Wéber (scree...,DECEMBER,30,Netflix / Bron Studios,[245],Pieces of a Woman

In [5]:
df_2020 = df[['Title','Cast and crew']]

In [6]:
df_2020

                     Title                                      Cast and crew
0               The Grudge  Nicolas Pesce (director/screenplay); Andrea Ri...
1               Underwater  William Eubank (director); Brian Duffield, Ada...
2              Like a Boss  Miguel Arteta (director); Sam Pitman, Adam Col...
3            Three Christs  Jon Avnet (director/screenplay); Eric Nazarian...
4        Inherit the Viper  Anthony Jerjen (director); Andrew Crabtree (sc...
..                     ...                                                ...
270       We Can Be Heroes  Robert Rodriguez (director/screenplay); Priyan...
271      News of the World  Paul Greengrass (director/screenplay); Luke Da...
272  One Night in Miami...  Regina King (director); Kemp Powers (screenpla...
273  Promising Young Woman  Emerald Fennell (director/screenplay); Carey M...
274      Pieces of a Woman  Kornél Mundruczó (director); Kata Wéber (scree...

[275 rows x 2 columns]

In [7]:
from tmdbv3api import TMDb
import json
import requests
tmdb = TMDb()
tmdb.api_key = '552927457b085828308d3b468f6bea5f'

In [8]:
from tmdbv3api import Movie
tmdb_movie = Movie() 
def get_genre(x):
    genres = []
    result = tmdb_movie.search(x)
    if not result:
      return np.NaN
    else:
      movie_id = result[0].id
      response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
      data_json = response.json()
      if data_json['genres']:
          genre_str = " " 
          for i in range(0,len(data_json['genres'])):
              genres.append(data_json['genres'][i]['name'])
          return genre_str.join(genres)
      else:
          return np.NaN

In [9]:
df_2020['genres'] = df_2020['Title'].map(lambda x: get_genre(str(x)))

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [10]:
df_2020

,Title,Cast and crew,genres
0,The Grudge,Nicolas Pesce (director/screenplay); Andrea Ri...,Horror Mystery Thriller
1,Underwater,"William Eubank (director); Brian Duffield, Ada...",Action Horror Science Fiction Thriller
2,Like a Boss,"Miguel Arteta (director); Sam Pitman, Adam Col...",Comedy
3,Three Christs,Jon Avnet (director/screenplay); Eric Nazarian...,Drama
4,Inherit the Viper,Anthony Jerjen (director); Andrew Crabtree (sc...,Crime Thriller Drama
...,...,...,...
270,We Can Be Heroes,Robert Rodriguez (director/screenplay); Priyan...,Action Fantasy Family Comedy
271,News of the World,Paul Greengrass (director/screenplay); Luke Da...,Drama Western Adventure
272,One Night in Miami...,Regina King (director); Kemp Powers (screenpla...,Drama
273,Promising Young Woman,Emerald Fennell (director/screenplay); Carey M...,Thriller Crime Drama
274,Pieces of a Woman,Kornél Mundruczó (director); Kata Wéber (scree...,Drama

In [11]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [12]:
df_2020['director_name'] = df_2020['Cast and crew'].map(lambda x: get_director(str(x)))

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [13]:
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [14]:
df_2020['actor_1_name'] = df_2020['Cast and crew'].map(lambda x: get_actor1(str(x)))

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [15]:
df_2020['Cast and crew']

0      Nicolas Pesce (director/screenplay); Andrea Ri...
1      William Eubank (director); Brian Duffield, Ada...
2      Miguel Arteta (director); Sam Pitman, Adam Col...
3      Jon Avnet (director/screenplay); Eric Nazarian...
4      Anthony Jerjen (director); Andrew Crabtree (sc...
                             ...
270    Robert Rodriguez (director/screenplay); Priyan...
271    Paul Greengrass (director/screenplay); Luke Da...
272    Regina King (director); Kemp Powers (screenpla...
273    Emerald Fennell (director/screenplay); Carey M...
274    Kornél Mundruczó (director); Kata Wéber (scree...
Name: Cast and crew, Length: 275, dtype: object

In [16]:
df_2020['actor_1_name']

0         Andrea Riseborough
1            Kristen Stewart
2            Tiffany Haddish
3               Richard Gere
4              Josh Hartnett
               ...
270    Priyanka Chopra Jonas
271                Tom Hanks
272        Kingsley Ben-Adir
273           Carey Mulligan
274            Vanessa Kirby
Name: actor_1_name, Length: 275, dtype: object

In [17]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [18]:
df_2020['actor_2_name'] = df_2020['Cast and crew'].map(lambda x: get_actor2(str(x)))

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [19]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [20]:
df_2020['actor_3_name'] = df_2020['Cast and crew'].map(lambda x: get_actor3(str(x)))

In [21]:
df_2020

,Title,Cast and crew,genres,director_name,actor_1_name,actor_2_name,actor_3_name
0,The Grudge,Nicolas Pesce (director/screenplay); Andrea Ri...,Horror Mystery Thriller,Nicolas Pesce,Andrea Riseborough,Demián Bichir,John Cho
1,Underwater,"William Eubank (director); Brian Duffield, Ada...",Action Horror Science Fiction Thriller,William Eubank,Kristen Stewart,Vincent Cassel,Jessica Henwick
2,Like a Boss,"Miguel Arteta (director); Sam Pitman, Adam Col...",Comedy,Miguel Arteta,Tiffany Haddish,Rose Byrne,Salma Hayek
3,Three Christs,Jon Avnet (director/screenplay); Eric Nazarian...,Drama,Jon Avnet,Richard Gere,Peter Dinklage,Walton Goggins
4,Inherit the Viper,Anthony Jerjen (director); Andrew Crabtree (sc...,Crime Thriller Drama,Anthony Jerjen,Josh Hartnett,Margarita Levieva,Chandler Riggs
...,...,...,...,...,...,...,...
270,We Can Be Heroes,Robert Rodriguez (director/screenplay); Priyan...,Action Fantasy Family Comedy,Robert Rodriguez,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin
271,News of the World,Paul Greengrass (director/screenplay); Luke Da...,Drama Western Adventure,Paul Greengrass,Tom Hanks,Helena Zengel,NaN
272,One Night in Miami...,Regina King (director); Kemp Powers (screenpla...,Drama,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge
273,Promising Young Woman,Emerald Fennell (director/screenplay); Carey M...,Thriller Crime Drama,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie
274,Pieces of a Woman,Kornél Mundruczó (director); Kata Wéber (scree...,Drama,Kornél Mundruczó,Vanessa Kirby,Shia LaBeouf,Molly Parker

In [22]:
df_2020 = df_2020.rename(columns={'Title':'movie_title'})

In [23]:
new_df20 = df_2020.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [24]:
new_df20

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
0,Nicolas Pesce,Andrea Riseborough,Demián Bichir,John Cho,Horror Mystery Thriller,The Grudge
1,William Eubank,Kristen Stewart,Vincent Cassel,Jessica Henwick,Action Horror Science Fiction Thriller,Underwater
2,Miguel Arteta,Tiffany Haddish,Rose Byrne,Salma Hayek,Comedy,Like a Boss
3,Jon Avnet,Richard Gere,Peter Dinklage,Walton Goggins,Drama,Three Christs
4,Anthony Jerjen,Josh Hartnett,Margarita Levieva,Chandler Riggs,Crime Thriller Drama,Inherit the Viper
...,...,...,...,...,...,...
270,Robert Rodriguez,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin,Action Fantasy Family Comedy,We Can Be Heroes
271,Paul Greengrass,Tom Hanks,Helena Zengel,NaN,Drama Western Adventure,News of the World
272,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge,Drama,One Night in Miami...
273,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie,Thriller Crime Drama,Promising Young Woman
274,Kornél Mundruczó,Vanessa Kirby,Shia LaBeouf,Molly Parker,Drama,Pieces of a Woman

In [25]:
new_df20['comb'] = new_df20['actor_1_name'] + ' ' + new_df20['actor_2_name'] + ' '+ new_df20['actor_3_name'] + ' '+ new_df20['director_name'] +' ' + new_df20['genres']

In [26]:
new_df20.isna().sum()

director_name     0
actor_1_name      0
actor_2_name      5
actor_3_name     28
genres            2
movie_title       0
comb             29
dtype: int64

In [27]:
new_df20 = new_df20.dropna(how='any')

In [28]:
new_df20.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [29]:
new_df20['movie_title'] = new_df20['movie_title'].str.lower()

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [30]:
new_df20

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Nicolas Pesce,Andrea Riseborough,Demián Bichir,John Cho,Horror Mystery Thriller,the grudge,Andrea Riseborough Demián Bichir John Cho Nico...
1,William Eubank,Kristen Stewart,Vincent Cassel,Jessica Henwick,Action Horror Science Fiction Thriller,underwater,Kristen Stewart Vincent Cassel Jessica Henwick...
2,Miguel Arteta,Tiffany Haddish,Rose Byrne,Salma Hayek,Comedy,like a boss,Tiffany Haddish Rose Byrne Salma Hayek Miguel ...
3,Jon Avnet,Richard Gere,Peter Dinklage,Walton Goggins,Drama,three christs,Richard Gere Peter Dinklage Walton Goggins Jon...
4,Anthony Jerjen,Josh Hartnett,Margarita Levieva,Chandler Riggs,Crime Thriller Drama,inherit the viper,Josh Hartnett Margarita Levieva Chandler Riggs...
...,...,...,...,...,...,...,...
269,Pete Docter,Jamie Foxx,Tina Fey,Graham Norton,Animation Comedy Fantasy Family,soul,Jamie Foxx Tina Fey Graham Norton Pete Docter ...
270,Robert Rodriguez,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin,Action Fantasy Family Comedy,we can be heroes,Priyanka Chopra Jonas Pedro Pascal YaYa Gossel...
272,Regina King,Kingsley Ben-Adir,Eli Goree,Aldis Hodge,Drama,one night in miami...,Kingsley Ben-Adir Eli Goree Aldis Hodge Regina...
273,Emerald Fennell,Carey Mulligan,Bo Burnham,Alison Brie,Thriller Crime Drama,promising young woman,Carey Mulligan Bo Burnham Alison Brie Emerald ...
274,Kornél Mundruczó,Vanessa Kirby,Shia LaBeouf,Molly Parker,Drama,pieces of a woman,Vanessa Kirby Shia LaBeouf Molly Parker Kornél...

In [31]:
old_df = pd.read_csv(r'C:\Users\HP\OneDrive\Desktop\mini-project\modular\recommendation_system\data\final_data.csv')

In [32]:
old_df

,Unnamed: 0,actor_1_name,actor_2_name,actor_3_name,comb,director_name,genres,movie_title
0,0,CCH Pounder,Joel David Moore,Wes Studi,CCH Pounder Joel David Moore Wes Studi James C...,James Cameron,Action Adventure Fantasy Sci-Fi,avatar
1,1,Johnny Depp,Orlando Bloom,Jack Davenport,Johnny Depp Orlando Bloom Jack Davenport Gore ...,Gore Verbinski,Action Adventure Fantasy,pirates of the caribbean: at world's end
2,2,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Christoph Waltz Rory Kinnear Stephanie Sigman ...,Sam Mendes,Action Adventure Thriller,spectre
3,3,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Tom Hardy Christian Bale Joseph Gordon-Levitt ...,Christopher Nolan,Action Thriller,the dark knight rises
4,4,Doug Walker,Rob Walker,unknown,Doug Walker Rob Walker unknown Doug Walker Doc...,Doug Walker,Documentary,star wars: episode vii - the force awakens ...
...,...,...,...,...,...,...,...,...
5871,5873,Will Smith,Tom Holland,Rashida Jones,Will Smith Tom Holland Rashida Jones Nick Brun...,"Nick Bruno, Troy Quane",Animation Action Adventure Comedy Family,spies in disguise
5872,5874,Saoirse Ronan,Emma Watson,Florence Pugh,Saoirse Ronan Emma Watson Florence Pugh Greta ...,Greta Gerwig,Drama Romance,little women
5873,5875,George MacKay,Dean-Charles Chapman,Mark Strong,George MacKay Dean-Charles Chapman Mark Strong...,Sam Mendes,War Drama Action Thriller,1917
5874,5876,Michael B. Jordan,Jamie Foxx,Brie Larson,Michael B. Jordan Jamie Foxx Brie Larson Desti...,Destin Daniel Cretton,Drama Crime History,just mercy
5875,5877,Alfre Woodard,Wendell Pierce,Aldis Hodge,Alfre Woodard Wendell Pierce Aldis Hodge Chino...,Chinonye Chukwu,Drama,clemency

In [33]:
final_df = old_df.append(new_df20,ignore_index=True)

In [34]:
final_df

,Unnamed: 0,actor_1_name,actor_2_name,actor_3_name,comb,director_name,genres,movie_title
0,0.0,CCH Pounder,Joel David Moore,Wes Studi,CCH Pounder Joel David Moore Wes Studi James C...,James Cameron,Action Adventure Fantasy Sci-Fi,avatar
1,1.0,Johnny Depp,Orlando Bloom,Jack Davenport,Johnny Depp Orlando Bloom Jack Davenport Gore ...,Gore Verbinski,Action Adventure Fantasy,pirates of the caribbean: at world's end
2,2.0,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Christoph Waltz Rory Kinnear Stephanie Sigman ...,Sam Mendes,Action Adventure Thriller,spectre
3,3.0,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Tom Hardy Christian Bale Joseph Gordon-Levitt ...,Christopher Nolan,Action Thriller,the dark knight rises
4,4.0,Doug Walker,Rob Walker,unknown,Doug Walker Rob Walker unknown Doug Walker Doc...,Doug Walker,Documentary,star wars: episode vii - the force awakens ...
...,...,...,...,...,...,...,...,...
6117,NaN,Jamie Foxx,Tina Fey,Graham Norton,Jamie Foxx Tina Fey Graham Norton Pete Docter ...,Pete Docter,Animation Comedy Fantasy Family,soul
6118,NaN,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin,Priyanka Chopra Jonas Pedro Pascal YaYa Gossel...,Robert Rodriguez,Action Fantasy Family Comedy,we can be heroes
6119,NaN,Kingsley Ben-Adir,Eli Goree,Aldis Hodge,Kingsley Ben-Adir Eli Goree Aldis Hodge Regina...,Regina King,Drama,one night in miami...
6120,NaN,Carey Mulligan,Bo Burnham,Alison Brie,Carey Mulligan Bo Burnham Alison Brie Emerald ...,Emerald Fennell,Thriller Crime Drama,promising young woman
6121,NaN,Vanessa Kirby,Shia LaBeouf,Molly Parker,Vanessa Kirby Shia LaBeouf Molly Parker Kornél...,Kornél Mundruczó,Drama,pieces of a woman

In [35]:
import os
final_df.to_csv(os.path.join(r'C:\Users\HP\OneDrive\Desktop\mini-project\modular\recommendation_system\data','main_data.csv'))

In [68]:
link = "https://en.wikipedia.org/wiki/List_of_American_films_of_2021"

In [69]:
df1 = pd.read_html(link, header=0)[2]
df2 = pd.read_html(link, header=0)[3]
df3 = pd.read_html(link, header=0)[4]
df4 = pd.read_html(link, header=0)[5]

In [70]:
df=df1.append(df2.append(df3.append(df4,ignore_index=True),ignore_index=True),ignore_index=True)

In [71]:
df

,.mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref.,Cast and crew,Opening,Opening.1,Production company,Ref.,Title
0,[2],Roseanne Liang (director/screenplay); Max Land...,JANUARY,1.0,Vertical Entertainment,NaN,Shadow in the Cloud
1,NaN,Ramin Bahrani (director/screenplay); Adarsh Go...,JANUARY,13.0,Netflix,NaN,The White Tiger
2,[3],Doug Liman (director); Steven Knight (screenpl...,JANUARY,14.0,HBO Max / Warner Bros. Pictures,NaN,Locked Down
3,[4],Simon Stone (director); Moira Buffini (screenp...,JANUARY,15.0,Netflix / Clerkenwell Films,NaN,The Dig
4,[5],"Mikael Håfström (director); Rob Yescombe, Rowa...",JANUARY,15.0,Netflix,NaN,Outside the Wire
...,...,...,...,...,...,...,...
353,NaN,Joel Coen (director/screenplay); Denzel Washin...,DECEMBER,25.0,Apple TV+ / A24 / IAC Films,[271],The Tragedy of Macbeth
354,NaN,Denzel Washington (director); Virgil Williams ...,DECEMBER,25.0,Columbia Pictures / Escape Artists / Bron Studios,[272],A Journal for Jordan
355,NaN,"Erwin brothers (directors); Jon Erwin, David A...",DECEMBER,25.0,Lionsgate,[273],American Underdog
356,NaN,Apichatpong Weerasethakul (director/acreenplay...,DECEMBER,26.0,Neon,[274],Memoria
357,NaN,NaN,DECEMBER,NaN,NaN,NaN,NaN

In [72]:
df['genres'] = df['Title'].map(lambda x: get_genre(str(x)))#calling the function uisng lambda function

In [73]:
df_2021 = df[['Title','Cast and crew','genres']]

In [74]:
df_2021

,Title,Cast and crew,genres
0,Shadow in the Cloud,Roseanne Liang (director/screenplay); Max Land...,Horror Action War
1,The White Tiger,Ramin Bahrani (director/screenplay); Adarsh Go...,Drama
2,Locked Down,Doug Liman (director); Steven Knight (screenpl...,Comedy Crime Drama
3,The Dig,Simon Stone (director); Moira Buffini (screenp...,Drama History
4,Outside the Wire,"Mikael Håfström (director); Rob Yescombe, Rowa...",Thriller Action Science Fiction
...,...,...,...
353,The Tragedy of Macbeth,Joel Coen (director/screenplay); Denzel Washin...,Drama War
354,A Journal for Jordan,Denzel Washington (director); Virgil Williams ...,Drama Romance
355,American Underdog,"Erwin brothers (directors); Jon Erwin, David A...",Drama
356,Memoria,Apichatpong Weerasethakul (director/acreenplay...,Drama Fantasy Mystery
357,NaN,NaN,Comedy

In [75]:
def get_director(x):
    if " (director)" in x:
        return x.split(" (director)")[0]
    elif " (directors)" in x:
        return x.split(" (directors)")[0]
    else:
        return x.split(" (director/screenplay)")[0]

In [76]:
df_2021['director_name'] = df_2021['Cast and crew'].map(lambda x: get_director(str(x)))

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [77]:
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [78]:
df_2021['actor_1_name'] = df_2021['Cast and crew'].map(lambda x: get_actor1(str(x)))

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [79]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [80]:
df_2021['actor_2_name'] = df_2021['Cast and crew'].map(lambda x: get_actor2(str(x)))

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [81]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [82]:

df_2021['actor_3_name'] = df_2021['Cast and crew'].map(lambda x: get_actor2(str(x)))

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [83]:
df_2021 = df_2021.rename(columns={'Title':'movie_title'})

In [84]:
new_df21 = df_2021.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [85]:
new_df21

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
0,Roseanne Liang,Chloë Grace Moretz,Taylor John Smith,Taylor John Smith,Horror Action War,Shadow in the Cloud
1,Ramin Bahrani,Adarsh Gourav,Rajkummar Rao,Rajkummar Rao,Drama,The White Tiger
2,Doug Liman,Anne Hathaway,Chiwetel Ejiofor,Chiwetel Ejiofor,Comedy Crime Drama,Locked Down
3,Simon Stone,Carey Mulligan,Ralph Fiennes,Ralph Fiennes,Drama History,The Dig
4,Mikael Håfström,Anthony Mackie,Damson Idris,Damson Idris,Thriller Action Science Fiction,Outside the Wire
...,...,...,...,...,...,...
353,Joel Coen,Denzel Washington,Frances McDormand,Frances McDormand,Drama War,The Tragedy of Macbeth
354,Denzel Washington,Michael B. Jordan,Chanté Adams,Chanté Adams,Drama Romance,A Journal for Jordan
355,Erwin brothers,Zachary Levi,Anna Paquin,Anna Paquin,Drama,American Underdog
356,Apichatpong Weerasethakul (director/acreenplay...,Apichatpong Weerasethakul (director/acreenplay...,Elkin Díaz,Elkin Díaz,Drama Fantasy Mystery,Memoria
357,nan,nan,NaN,NaN,Comedy,NaN

In [86]:
new_df21['comb'] = new_df21['actor_1_name'] + ' ' + new_df21['actor_2_name'] + ' '+ new_df21['actor_3_name'] + ' '+ new_df21['director_name'] +' ' + new_df21['genres']

In [88]:
new_df21.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     8
actor_3_name     8
genres           1
movie_title      1
comb             9
dtype: int64

In [90]:
new_df21 = new_df21.dropna(how='any')

In [91]:
new_df21.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [92]:
new_df20['movie_title'] = new_df20['movie_title'].str.lower()

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [93]:
new_df21

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Roseanne Liang,Chloë Grace Moretz,Taylor John Smith,Taylor John Smith,Horror Action War,Shadow in the Cloud,Chloë Grace Moretz Taylor John Smith Taylor Jo...
1,Ramin Bahrani,Adarsh Gourav,Rajkummar Rao,Rajkummar Rao,Drama,The White Tiger,Adarsh Gourav Rajkummar Rao Rajkummar Rao Rami...
2,Doug Liman,Anne Hathaway,Chiwetel Ejiofor,Chiwetel Ejiofor,Comedy Crime Drama,Locked Down,Anne Hathaway Chiwetel Ejiofor Chiwetel Ejiofo...
3,Simon Stone,Carey Mulligan,Ralph Fiennes,Ralph Fiennes,Drama History,The Dig,Carey Mulligan Ralph Fiennes Ralph Fiennes Sim...
4,Mikael Håfström,Anthony Mackie,Damson Idris,Damson Idris,Thriller Action Science Fiction,Outside the Wire,Anthony Mackie Damson Idris Damson Idris Mikae...
...,...,...,...,...,...,...,...
352,Matthew Vaughn,Ralph Fiennes,Gemma Arterton,Gemma Arterton,Action Adventure Thriller War Mystery,The King's Man,Ralph Fiennes Gemma Arterton Gemma Arterton Ma...
353,Joel Coen,Denzel Washington,Frances McDormand,Frances McDormand,Drama War,The Tragedy of Macbeth,Denzel Washington Frances McDormand Frances Mc...
354,Denzel Washington,Michael B. Jordan,Chanté Adams,Chanté Adams,Drama Romance,A Journal for Jordan,Michael B. Jordan Chanté Adams Chanté Adams De...
355,Erwin brothers,Zachary Levi,Anna Paquin,Anna Paquin,Drama,American Underdog,Zachary Levi Anna Paquin Anna Paquin Erwin bro...
356,Apichatpong Weerasethakul (director/acreenplay...,Apichatpong Weerasethakul (director/acreenplay...,Elkin Díaz,Elkin Díaz,Drama Fantasy Mystery,Memoria,Apichatpong Weerasethakul (director/acreenplay...

In [94]:
old_df = pd.read_csv(r'C:\Users\HP\OneDrive\Desktop\mini-project\modular\recommendation_system\data\main_data.csv')

In [95]:
old_df

,Unnamed: 0,Unnamed: 0.1,actor_1_name,actor_2_name,actor_3_name,comb,director_name,genres,movie_title
0,0,0.0,CCH Pounder,Joel David Moore,Wes Studi,CCH Pounder Joel David Moore Wes Studi James C...,James Cameron,Action Adventure Fantasy Sci-Fi,avatar
1,1,1.0,Johnny Depp,Orlando Bloom,Jack Davenport,Johnny Depp Orlando Bloom Jack Davenport Gore ...,Gore Verbinski,Action Adventure Fantasy,pirates of the caribbean: at world's end
2,2,2.0,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Christoph Waltz Rory Kinnear Stephanie Sigman ...,Sam Mendes,Action Adventure Thriller,spectre
3,3,3.0,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Tom Hardy Christian Bale Joseph Gordon-Levitt ...,Christopher Nolan,Action Thriller,the dark knight rises
4,4,4.0,Doug Walker,Rob Walker,unknown,Doug Walker Rob Walker unknown Doug Walker Doc...,Doug Walker,Documentary,star wars: episode vii - the force awakens ...
...,...,...,...,...,...,...,...,...,...
6117,6117,NaN,Jamie Foxx,Tina Fey,Graham Norton,Jamie Foxx Tina Fey Graham Norton Pete Docter ...,Pete Docter,Animation Comedy Fantasy Family,soul
6118,6118,NaN,Priyanka Chopra Jonas,Pedro Pascal,YaYa Gosselin,Priyanka Chopra Jonas Pedro Pascal YaYa Gossel...,Robert Rodriguez,Action Fantasy Family Comedy,we can be heroes
6119,6119,NaN,Kingsley Ben-Adir,Eli Goree,Aldis Hodge,Kingsley Ben-Adir Eli Goree Aldis Hodge Regina...,Regina King,Drama,one night in miami...
6120,6120,NaN,Carey Mulligan,Bo Burnham,Alison Brie,Carey Mulligan Bo Burnham Alison Brie Emerald ...,Emerald Fennell,Thriller Crime Drama,promising young woman
6121,6121,NaN,Vanessa Kirby,Shia LaBeouf,Molly Parker,Vanessa Kirby Shia LaBeouf Molly Parker Kornél...,Kornél Mundruczó,Drama,pieces of a woman

In [96]:
final_df = old_df.append(new_df20,ignore_index=True)

In [3]:
final_df

NameError: name 'final_df' is not defined

In [98]:

final_df.to_csv(os.path.join(r'C:\Users\HP\OneDrive\Desktop\mini-project\modular\recommendation_system\data','Final_Data.csv'))